# Automatic overrides for local development. DockerHub builds must specify "-f docker-compose.yml" explicitly.
services:
  odata-manager-app:
    environment:
      - JPDA_SUSPEND=y # Enable debugging for development
    expose:
      - "8000"
    ports:
      - "8000:8000" # Map debugging port for development
      - "8080:8080"
