version: '3'
services:
  odata-manager-app:
    restart: on-failure
    build: ./
    expose:
      - "10222"
    ports:
      - 10222:10222
    environment:
      - WAIT_HOSTS
    depends_on:
      - docker-mysql
