version: '3'
services:
  odata-manager-app:
    restart: on-failure
    build: ./
    expose:
      - "8080"
      - "8000"
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      - SQL_HOST
      - SQL_USER
      - SQL_PASSWORD
      - SQL_CONNECTION_STR
      - SQL_DB_DRIVER
    volumes:
      - ./target:/usr/local/tomcat/webapps
#    depends_on:
#      - docker-mysql
