version: '3'
services:
  odata-manager-app:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      - WAIT_HOSTS
#    depends_on:
#      - docker-mysql
