name: RESO Web API Reference Server Development Enviroment CI/CD

on:
  push:
    branches:
      - "develop"
      - "feature/*-development"
      - "release/*-development"
      - "hotfix/*-development"
      - "support/*-development"

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    env:
      ENVIRONMENT: dev
      DOCKER_BUILDKIT: 1
    steps:

      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run ENV setup script
        run: |
          chmod +x ./docker/scripts/setup_build_env.sh
          ./docker/scripts/setup_build_env.sh

      - name: Run build script
        run: |
          chmod +x ./docker/scripts/build.sh
          ./docker/scripts/build.sh

      - name: Run docker-compose to make the images
        run: docker-compose build

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push to Dockerhub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: michaelpede/reso-web-api-reference-server_odata-manager-app:latest
# We don't really need the SQL server "build" as it's a default Docker build
#      - name: Run docker build for the WEB API Server Database
#        run: docker save --output database-server.tar mysql/mysql-server
